<?php
	$months = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
?>
<div class="portfolio-step-header">
	<div class="row">
		<h1>Update Risk Free Rates</h1>
	</div>
</div>
<div class="row">
	<ol class="breadcrumb">
		<li>
			<a href="/"> <i class="icon-home"></i> Home</a>
		</li>
		<li class="active">
			<i class="icon-table"></i> Risk Free Rates
		</li>
	</ol>
</div>
<div class="row">
	<div class="panel panel-primary">
		<div class="panel-heading">
			Risk Free Rates
		</div>
		<div class="panel-body">
			<div class="alert alert-info">
		        <strong>Heads up!</strong> Please enter numerical values. Values are auto-saved after blur.  
		      </div>
    		<table class="table table-bordered table-hover table-striped">
        		<thead>
					<tr>
						<th>Year</th>
						<?php
							foreach($months as $month){
								?>
								<th><?php echo $month?></th>
								<?php
							}
						?>
					</tr>
				</thead>
    			<tbody>
        			<?php
	        			$start = intval(date("Y"))+2;
	        			for($i=$start;$i>=1999;$i--){
	        				?>
	        				<tr>
	        					<td><?php echo $i?></td>
	        					<?php
	        					
									foreach($months as $month){?>
										<?php
											$value = "";
											foreach($this->risk_free_rates as $rate){
												if ($rate["month"]==$month&&$rate["year"]==$i){
													$value = number_format($rate["value"], 2);
													break;
												}
											}
										?>
										<td><input type="text" class="form-control risk_value" data-month="<?php echo $month?>" data-year="<?php echo $i?>" value="<?php echo $value?>"/></td>
										<?php
									}?>
							
	        				</tr>
	        				<?php
	        			}
	        		?>	
    			</tbody>
    			<tfoot>
					<th>Year</th>
					<?php
						foreach($months as $month){
							?>
							<th><?php echo $month?></th>
							<?php
						}
					?>
    			</tfoot>
    		</table>
		</div>
	</div>
</div>